In [1]:
import pandas as pd

csv_path = "adultobesity.csv"

adult_data = pd.read_csv(csv_path)

adult_data.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2017,2017,WA,Washington,Behavioral Risk Factor Surveillance System,Fruits and Vegetables,Fruits and Vegetables - Behavior,Percent of adults who report consuming fruit l...,NaN,Value,...,"(47.522278629, -120.47001079)",FV,FV1,Q018,VALUE,53,Income,"Less than $15,000",INC,INCLESS15
1,2017,2017,MA,Massachusetts,Behavioral Risk Factor Surveillance System,Fruits and Vegetables,Fruits and Vegetables - Behavior,Percent of adults who report consuming fruit l...,NaN,Value,...,"(42.27687047, -72.082690675)",FV,FV1,Q018,VALUE,25,Race/Ethnicity,Hispanic,RACE,RACEHIS
2,2017,2017,KY,Kentucky,Behavioral Risk Factor Surveillance System,Fruits and Vegetables,Fruits and Vegetables - Behavior,Percent of adults who report consuming fruit l...,NaN,Value,...,"(37.645970271, -84.774971048)",FV,FV1,Q018,VALUE,21,Race/Ethnicity,Asian,RACE,RACEASN
3,2017,2017,VT,Vermont,Behavioral Risk Factor Surveillance System,Fruits and Vegetables,Fruits and Vegetables - Behavior,Percent of adults who report consuming fruit l...,NaN,Value,...,"(43.625381239, -72.517640791)",FV,FV1,Q018,VALUE,50,Race/Ethnicity,Asian,RACE,RACEASN
4,2017,2017,NM,New Mexico,Behavioral Risk Factor Surveillance System,Fruits and Vegetables,Fruits and Vegetables - Behavior,Percent of adults who report consuming fruit l...,NaN,Value,...,"(34.520880952, -106.240580985)",FV,FV1,Q018,VALUE,35,Gender,Male,GEN,MALE

In [19]:
# grouped_adult_data = adult_data.groupby(["LocationDesc"])
# grouped_adult_data.head()
# grouped_adult_data.count()["LocationDesc"]

adult_obesity = adult_data.loc[(adult_data["QuestionID"] == "Q036") & (adult_data["YearStart"] == 2020) & (adult_data["StratificationCategoryId1"] == "INC")].reset_index(drop = "True")

# categories = adult_obesity["Stratification1"].unique()

# categories

# adult_fruit_consumption = pd.DataFrame(columns = ["Male", "Female", ""])

adult_obesity.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2020,2020,PR,Puerto Rico,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(18.220833, -66.590149)",OWS,OWS1,Q036,VALUE,72,Income,"$35,000 - $49,999",INC,INC3550
1,2020,2020,NV,Nevada,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(39.493240390000494, -117.07184056399967)",OWS,OWS1,Q036,VALUE,32,Income,"Less than $15,000",INC,INCLESS15
2,2020,2020,SC,South Carolina,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(33.998821303000454, -81.04537120699968)",OWS,OWS1,Q036,VALUE,45,Income,"$50,000 - $74,999",INC,INC5075
3,2020,2020,OK,Oklahoma,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(35.47203135600046, -97.52107021399968)",OWS,OWS1,Q036,VALUE,40,Income,"$75,000 or greater",INC,INC75PLUS
4,2020,2020,MD,Maryland,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(39.29058096400047, -76.60926011099963)",OWS,OWS1,Q036,VALUE,24,Income,"$50,000 - $74,999",INC,INC5075

In [17]:
adult_obesity.groupby()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2020,2020,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
1,2020,2020,GA,Georgia,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.83968109300048, -83.62758034599966)",OWS,OWS1,Q036,VALUE,13,Gender,Male,GEN,MALE
2,2020,2020,MA,Massachusetts,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(42.27687047000046, -72.08269067499964)",OWS,OWS1,Q036,VALUE,25,Race/Ethnicity,Hispanic,RACE,RACEHIS
3,2020,2020,PR,Puerto Rico,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(18.220833, -66.590149)",OWS,OWS1,Q036,VALUE,72,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI
4,2020,2020,PR,Puerto Rico,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(18.220833, -66.590149)",OWS,OWS1,Q036,VALUE,72,Race/Ethnicity,Non-Hispanic White,RACE,RACEWHT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,2020,2020,ME,Maine,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(45.254228894000505, -68.98503133599962)",OWS,OWS1,Q036,VALUE,23,Education,High school graduate,EDU,EDUHSGRAD
330,2020,2020,KY,Kentucky,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.645970271000465, -84.77497104799966)",OWS,OWS1,Q036,VALUE,21,Education,College graduate,EDU,EDUCOGRAD
337,2020,2020,MS,Mississippi,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.745510099000455, -89.53803082499968)",OWS,OWS1,Q036,VALUE,28,Income,Data not reported,INC,INCNR
347,2020,2020,AR,Arkansas,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(34.74865012400045, -92.27449074299966)",OWS,OWS1,Q036,VALUE,5,Education,High school graduate,EDU,EDUHSGRAD
376,2020,2020,AR,Arkansas,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(34.74865012400045, -92.27449074299966)",OWS,OWS1,Q036,VALUE,5,Race/Ethnicity,2 or more races,RACE,RACE2PLUS

In [22]:
poverty_csv = "poverty_stats/poverty_csv"

poverty_data = pd.read_csv(poverty_csv)

poverty_data.head()

,Year,State FIPS,Postal Code,Name,Poverty Percent All Ages,Median Household Income,Poverty Estimate Ages 5-17,Poverty Percent Ages 5-17
0,2003,0,US,United States,12.5,"43,318","8,399,573",16.1
1,2004,0,US,United States,12.7,"44,334","8,430,886",16.2
2,2005,0,US,United States,13.3,46242,8765541,17.0
3,2006,0,US,United States,13.3,48451,8700048,16.7
4,2007,0,US,United States,13.0,50740,8499844,16.4

In [23]:
state_capitals_csv = "poverty_stats/us-state-capitals.csv"

capitals = pd.read_csv(state_capitals_csv)

capitals.rename(["origi"])

       origin     blahblah   latitude   longitude
0         ATL        12.35  33.636666  -84.428066
1     Arizona      Phoenix  33.448143 -112.096962
2    Arkansas  Little Rock  34.746613  -92.288986
3  California   Sacramento  38.576668 -121.493629
4    Colorado       Denver  39.739227 -104.984856

In [ ]:
heatmap_poverty = pd.merge(poverty_data, capitals, on = [])